{% set name = "pyroma" %}
{% set import = "pyroma" %}
{% set entrypoint = "pyroma" %}
{% set version = "4.2" %}
{% set sha256 = "6c727dc4a7a10e12274faed5fb47ebd499ca0821995befec98e3cfcaf1e7383c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - {{ entrypoint }} = {{ import }}:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - docutils
    - packaging
    - pygments  # Required internally by docutils for readme check to work
    - python >={{ python_min }}
    - python-build >=0.7.0
    - requests
    - setuptools >=42
    - trove-classifiers >=2022.6.26

test:
  requires:
    - pip >=21  # For pip check
    - setuptools >=60
    - python {{ python_min }}

  source_files:
    # Test data to copy to installed package
    - {{ import }}/testdata

  imports:
    - {{ import }}

  commands:
    - pip check
    - {{ entrypoint }} --help
    # Copy the testdata into the expected place, sincei it isn't normally installed with the package
    - cp -r $SRC_DIR/{{ import }}/testdata $(python -c 'from pathlib import Path; import {{ import }}; print(Path({{ import }}.__file__).parent)')/testdata
    - python -b -X dev -m unittest -v pyroma.tests

about:
  home: https://github.com/regebro/pyroma/
  license: MIT
  license_file: LICENSE.txt
  summary: Test your project's packaging friendliness
  description: |
    Pyroma rhymes with aroma, and is a product aimed at giving a rating of how well a Python project complies with the best practices of the Python packaging ecosystem, primarily PyPI, pip, Distribute etc, as well as a list of issues that could be improved.
    The aim of this is both to help people make a project that is nice and usable, but also to improve the quality of Python third-party software, making it easier and more enjoyable to use the vast array of available modules for Python.
    It’s written so that there are a library with methods to call from Python, as well as a script, also called pyroma.
  dev_url: https://github.com/regebro/pyroma
  doc_url: https://github.com/regebro/pyroma/blob/master/README.rst

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - jakirkham
